[package]
name = "rust-mcd"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.7.4"
lazy_static = "1.4.0"
byteorder = "1.4.3"
tempfile = "3.3.0"
log = "0.4.17"
anyhow = "1.0.69"
bitfield-struct = "0.3.2"

[build-dependencies]
bindgen = "0.64.0"