[package]
name = "rust-mcd"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.7.4"
lazy_static = "1.4.0"
byteorder = "1.4.3"
log = "0.4.17"
anyhow = "1.0.69"

[build-dependencies]
bindgen = "0.69.4"

[features]
# Enable if using DAS version 8 over version 7
dasv8 = []
